start:
	python3 ./server.py $p $t msn-api 8889

start1:
	python3 ./server.py 8012 bcd msn-api 8889

start2:
	python3 ./server.py 8013 gccs msn-api 8889

start3:
	python3 ./server.py 8014 iamd msn-api 8889

start4:
	python3 ./server.py 8015 intel msn-api 8889

start5:
	python3 ./server.py 8016 freq msn-api 8889

start6:
	python3 ./server.py 8017 wx msn-api 8889

test:
	curl http://localhost:$p
