start:
	python3 ./msn-data-server.py $p $t

start1:
	python3 ./msn-data-server.py 8012 bcd

start2:
	python3 ./msn-data-server.py 8013 gccs

start3:
	python3 ./msn-data-server.py 8014 iamd

start4:
	python3 ./msn-data-server.py 8015 intel

start5:
	python3 ./msn-data-server.py 8016 freq

start6:
	python3 ./msn-data-server.py 8017 wx

test:
	curl http://localhost:$p
