start:
	python3 ./server.py $p $t msn-api 8889

start1:
	python3 ./server.py 8008 tv-01 msn-api 8889

start2:
	python3 ./server.py 8009 tv-02 msn-api 8889

start3:
	python3 ./server.py 8010 tv-05 msn-api 8889

start4:
	python3 ./server.py 8011 tv-06 msn-api 8889

test:
	curl http://localhost:$p
