start:
	python3 ./mx-data-server.py $p $t

start1:
	python3 ./mx-data-server.py 8008 tv-01

start2:
	python3 ./mx-data-server.py 8009 tv-02

start3:
	python3 ./mx-data-server.py 8010 tv-05

start4:
	python3 ./mx-data-server.py 8011 tv-06

test:
	curl http://localhost:$p
