start:
	python3 ./data-server.py $p $f

start1:
	python3 ./data-server.py 8008 data1.json

start2:
	python3 ./data-server.py 8009 data2.json

start3:
	python3 ./data-server.py 8010 data3.json

start4:
	python3 ./data-server.py 8011 data4.json

test:
	curl http://localhost:$p
